export const PGAS_NEW_CONTROL_PLANE_CONTROLS = [
  'ask',
  'abort',
  'new',
  'history',
  'status',
  'resume',
  'help',
] as const;

export type PgasNewControlPlaneControl = (typeof PGAS_NEW_CONTROL_PLANE_CONTROLS)[number];

export const PGAS_NEW_SESSION_CONTROLS = [
  'new',
  'abort',
  'status',
  'history',
  'resume',
  'help',
] as const satisfies readonly PgasNewControlPlaneControl[];

export type PgasNewSessionControl = (typeof PGAS_NEW_SESSION_CONTROLS)[number];

export function isPgasNewSessionControl(value: string | undefined): value is PgasNewSessionControl {
  return PGAS_NEW_SESSION_CONTROLS.includes(value as PgasNewSessionControl);
}

export function renderControlPlaneControlsYaml(program: string): string {
  return [
    '    ask:',
    '      title: Ask',
    '      aliases: ["/ask"]',
    '      args:',
    '        query:',
    '          type: string',
    '          required: true',
    '          capture: rest',
    '      dispatch:',
    '        - op: create_session',
    '          as: session',
    `          program: "${program}"`,
    '          domain_context:',
    '            query: "$args.query"',
    '        - op: trigger',
    '          session: "$session.id"',
    '          channel: user_text',
    '          payload: "$args.query"',
    '          mode: async',
    '    abort:',
    '      title: Abort run',
    '      aliases: ["/abort", "/stop"]',
    '      availability:',
    '        when: "active_session.running"',
    '      dispatch:',
    '        - op: abort_session',
    '          session: "$active_session.id"',
    '      presentation:',
    '        priority: destructive',
    '        confirm: true',
    '    new:',
    '      title: New session',
    '      aliases: ["/new", "/reset", "/restart"]',
    '      dispatch:',
    '        - op: create_session',
    '          as: session',
    `          program: "${program}"`,
    '      presentation:',
    '        priority: secondary',
    '    history:',
    '      title: Recent sessions',
    '      aliases: ["/history", "/recent"]',
    '      dispatch:',
    '        - op: list_sessions',
    '          as: sessions',
    '      presentation:',
    '        priority: secondary',
    '    status:',
    '      title: Status',
    '      aliases: ["/status"]',
    '      availability:',
    '        when: "active_session"',
    '      dispatch:',
    '        - op: render_session',
    '          session: "$active_session.id"',
    '          view: status',
    '      presentation:',
    '        priority: contextual',
    '    resume:',
    '      title: Resume',
    '      aliases: ["/resume"]',
    '      availability:',
    '        when: "active_session"',
    '      dispatch:',
    '        - op: send_runtime_control',
    '          session: "$active_session.id"',
    '          control: resume',
    '      presentation:',
    '        priority: contextual',
    '    help:',
    '      title: Help',
    '      aliases: ["/help"]',
    '      dispatch:',
    '        - op: render_help',
    '      presentation:',
    '        priority: secondary',
  ].join('\n');
}
