import { dump, load } from 'js-yaml';
import { PGAS_SERVER_VERSION } from '../../pgas-new/version.js';

/**
 * The engine's canonical root-key block order (`validationOptions.blueprint`).
 * Both emissions walk this list in order, so both are canonical BY
 * CONSTRUCTION: `modularSpecFilesFor` for the `import:` manifest, and
 * `canonicalBlueprintRootOrder` for the monolithic single-file `spec_yaml`.
 * pgas#946 makes `blueprint: 'strict'` the default in v6, so this order is
 * load-bearing. It is pinned by
 * `tests/unit/synthesized-modular-spec.test.ts` ("loads the modular emission
 * under blueprint: strict"), which also pins the `render:` deliverable slot
 * (after `view`, before `policy`), and by
 * `tests/unit/synthesized-monolithic-spec.test.ts`, which pins the literal
 * emitted root-key order. Reordering or misfiling a key here regresses the
 * whole emission; both failure modes are covered by those tests.
 *
 * NOTE for the modular path: the strict loader TOLERATES a non-canonical
 * `import:` order (`parseImportBlock` re-walks the engine's own block list),
 * so a strict load alone does NOT catch a misordered block list there — only
 * the explicit order assertion does.
 */
export const BLUEPRINT_SPEC_BLOCKS = [
  'identity',
  'domain',
  'lifecycle',
  'channels',
  'actions',
  'guidance',
  'delegation',
  'validation',
  'view',
  'render',
  'policy',
] as const;

export type BlueprintSpecBlock = typeof BLUEPRINT_SPEC_BLOCKS[number];

export interface SynthesizedSpecFile {
  path: string;
  content: string;
}

/**
 * Human-readable role for each canonical blueprint block, derived from the
 * 11-block definition in
 * `docs/superpowers/specs/2026-08-13-foundry-blueprint-convergence-design.md:40-50`.
 * These strings are FIXED, general across all domains, and carry no
 * domain/deliverable content -- they are used only to caption the emitted spec
 * files so a human reading a generated `programs/<name>/` directory can orient.
 */
const BLOCK_ROLE: Record<BlueprintSpecBlock, string> = {
  identity: 'name, version, description, kind, metadata',
  domain: 'schema (world shape) + engine-owned/derived path decls',
  lifecycle: 'modes, initial, terminal, transitions',
  channels: 'user IO + delegation channels',
  actions: 'action_map (vocabulary + mutations + arg_schema)',
  guidance: 'per-mode prompts / $ref fragments',
  delegation: 'conversational, requires_delegations, result_schema',
  validation: 'preconditions, invariants, recovery_steers, no_action_escapes, bounds',
  view: 'view: + derived_paths',
  render: 'render: deliverable profile',
  policy: 'declarative policies (delegation/continuation/reliability/artifact/query)',
};

const BANNER_RULE = `# ${'='.repeat(76)}`;

// Provenance line reused across every emitted file. The version is the pinned
// checked engine version, never invented text.
const PROVENANCE_COMMENT =
  `# Generated by pgas-new · @simodelne/pgas-server ${PGAS_SERVER_VERSION} · edit the design, not this file.`;

function blockBannerFor(block: BlueprintSpecBlock): string {
  const position = BLUEPRINT_SPEC_BLOCKS.indexOf(block) + 1;
  return [
    BANNER_RULE,
    `# Blueprint block ${position}/${BLUEPRINT_SPEC_BLOCKS.length} — ${block}`,
    `# Role: ${BLOCK_ROLE[block]}`,
    PROVENANCE_COMMENT,
    BANNER_RULE,
  ].join('\n');
}

function programNameFor(spec: Record<string, unknown>): string {
  return typeof spec.name === 'string' && spec.name.length > 0 ? spec.name : '(unnamed program)';
}

/**
 * Build the manifest `specs.yml` content: a human banner naming the program,
 * then a hand-emitted `import:` list with a one-line role comment above each
 * entry, then the remaining manifest values (`patterns`) rendered by `dump`.
 * Hand-emitting the import list is what lets the per-entry role comments survive
 * (js-yaml `dump` strips comments); the assembled string still parses to the
 * same `{ import, ...manifestValues }` mapping the loader consumes.
 */
function manifestContentFor(
  spec: Record<string, unknown>,
  importMap: Record<string, string>,
  manifestValues: Record<string, unknown>,
): string {
  const header = [
    BANNER_RULE,
    `# ${programNameFor(spec)} — program specification manifest`,
    '# Wires the canonical blueprint blocks below.',
    PROVENANCE_COMMENT,
    BANNER_RULE,
  ].join('\n');

  const importLines = ['import:'];
  for (const block of BLUEPRINT_SPEC_BLOCKS) {
    const path = importMap[block];
    if (!path) {
      continue;
    }
    importLines.push(`  # ${BLOCK_ROLE[block]}`);
    importLines.push(`  ${block}: ${path}`);
  }

  let body = `${importLines.join('\n')}\n`;
  if (Object.keys(manifestValues).length > 0) {
    body += dump(manifestValues, yamlOptions());
  }

  return `${header}\n${body}`;
}

const BLOCK_KEY_ORDER: Record<BlueprintSpecBlock, readonly string[]> = {
  identity: [
    'name',
    'version',
    'description',
    'kind',
    'metadata',
    'features',
    'pure',
    'disallow_raw_mutation_authoring',
  ],
  domain: [
    'schema',
    'reference_data',
    'ephemeral',
    'advisory_schema',
    'activation_providers',
    'decision_schema',
    'keyed_collections',
    'merge_collections',
    'derived_paths',
    'derived_state_machines',
    'collection_finalizers',
    'reactions',
    'collection',
    'collections',
  ],
  lifecycle: [
    'modes',
    'initial',
    'terminal',
    'topology',
    'termination',
    'status_on_terminal',
    'proceeds_to',
    'notice_terminal_exemptions',
  ],
  channels: [
    'channels',
    'fallback',
    'ingestion',
    'ingestion_guidance',
    'ingestion_root_passthrough',
    'agent_nodes',
    'schedule',
    'command_grammar',
    'control_plane',
    'integrations',
  ],
  actions: [
    'action_map',
    'tools',
    'confirmation_pairing',
  ],
  guidance: [
    'preamble',
    'prompts',
    'guidance',
  ],
  delegation: [
    'delegation',
    'children',
    'requires_delegations',
  ],
  validation: [
    'preconditions',
    'invariants',
    'finalization_requires',
    'finalization_gated_actions',
    'schema_invariants',
    'bounded_rework',
    'recovery_steers',
    'no_action_escapes',
    'repair_bound',
    'invariant',
  ],
  view: [
    'projection',
    'view',
    'initial_crystallize',
  ],
  render: [
    'render',
    'artifact_bundle',
  ],
  policy: [
    'policies',
    'notebook',
  ],
};

/**
 * Manifest keys are block-less: the engine files them under a synthetic
 * `manifest` block whose index is -1, and rejects any manifest key that does
 * NOT lead the spec (`MANIFEST_NOT_LEADING`). They are emitted first, in this
 * order, by `canonicalBlueprintRootOrder`.
 */
const MANIFEST_KEY_ORDER = ['import', 'patterns'] as const;
const MANIFEST_KEYS = new Set<string>(MANIFEST_KEY_ORDER);
const KEY_TO_BLOCK = new Map<string, BlueprintSpecBlock>(
  BLUEPRINT_SPEC_BLOCKS.flatMap((block) =>
    BLOCK_KEY_ORDER[block].map((key) => [key, block] as const)),
);

/** The canonical blueprint block a synthesized spec root key belongs to. */
export function blueprintBlockForRootKey(key: string): BlueprintSpecBlock | undefined {
  return KEY_TO_BLOCK.get(key);
}

interface BlueprintPartition {
  manifest: Record<string, unknown>;
  blocks: Map<BlueprintSpecBlock, Record<string, unknown>>;
}

/**
 * Split a synthesized spec's ROOT keys into the manifest keys plus the
 * canonical blueprint blocks, walking `BLUEPRINT_SPEC_BLOCKS` in order so the
 * result is canonical BY CONSTRUCTION. Every root-key consumer (the modular
 * `import:` emission and the monolithic `spec_yaml` emission) goes through
 * this one partition, so the two emissions can never disagree about which
 * block a key belongs to or what order the blocks come in.
 *
 * Fail-closed: an unmapped root key throws rather than being silently
 * appended, because a key the foundry cannot place is a key the engine's
 * blueprint gate may place differently.
 */
function partitionSpecByBlueprintBlock(spec: Record<string, unknown>): BlueprintPartition {
  const manifest: Record<string, unknown> = {};
  const grouped = new Map<BlueprintSpecBlock, Record<string, unknown>>();

  for (const [key, value] of Object.entries(spec)) {
    if (MANIFEST_KEYS.has(key)) {
      manifest[key] = value;
      continue;
    }
    const block = KEY_TO_BLOCK.get(key);
    if (!block) {
      throw new Error(`cannot modularize synthesized spec: top-level key "${key}" is not mapped to a blueprint block`);
    }
    const target = grouped.get(block) ?? {};
    target[key] = value;
    grouped.set(block, target);
  }

  const blocks = new Map<BlueprintSpecBlock, Record<string, unknown>>();
  for (const block of BLUEPRINT_SPEC_BLOCKS) {
    const content = sortedBlockContent(block, grouped.get(block));
    if (content) {
      blocks.set(block, content);
    }
  }
  return { manifest, blocks };
}

/**
 * Regroup a synthesized spec's ROOT keys into canonical blueprint block order
 * (manifest keys first, then `BLUEPRINT_SPEC_BLOCKS` in order, then each
 * block's own `BLOCK_KEY_ORDER`). Values are carried by reference and no key
 * is added, dropped, or renamed — YAML key ORDER compiles to nothing, so the
 * `Specification` the engine compiles is unchanged.
 *
 * This is what makes the MONOLITHIC single-file `spec_yaml` emission load
 * under `blueprint: 'strict'` (pgas#946 makes strict the default in v6). The
 * modular emission was already strict-clean because `modularSpecFilesFor`
 * walks the same partition; this exports that property to every other place
 * the foundry dumps a whole spec.
 */
export function canonicalBlueprintRootOrder(spec: Record<string, unknown>): Record<string, unknown> {
  const { manifest, blocks } = partitionSpecByBlueprintBlock(spec);
  const ordered: Record<string, unknown> = {};

  for (const key of MANIFEST_KEY_ORDER) {
    if (Object.prototype.hasOwnProperty.call(manifest, key)) {
      ordered[key] = manifest[key];
    }
  }
  for (const block of BLUEPRINT_SPEC_BLOCKS) {
    for (const [key, value] of Object.entries(blocks.get(block) ?? {})) {
      ordered[key] = value;
    }
  }
  return ordered;
}

export function modularSpecFilesFor(spec: Record<string, unknown>): SynthesizedSpecFile[] {
  const manifestValues = manifestValuesFor(spec);
  const { blocks } = partitionSpecByBlueprintBlock(spec);

  const importMap: Record<string, string> = {};
  const blockFiles: SynthesizedSpecFile[] = [];
  for (const block of BLUEPRINT_SPEC_BLOCKS) {
    const content = blocks.get(block);
    if (!content) {
      continue;
    }
    const path = `${block}.yml`;
    importMap[block] = path;
    // Prepend a human-readable banner ABOVE the real block content. The banner
    // is comments only, but the file is never comment-only (empty blocks are
    // skipped above), so the engine's strict import resolver (5.6.0+, pinned at
    // 6.6.1 today) still parses each fragment to a YAML mapping. Comments compile
    // to nothing, so behavior is unchanged.
    blockFiles.push({ path, content: `${blockBannerFor(block)}\n${dump(content, yamlOptions())}` });
  }

  return [
    { path: 'specs.yml', content: manifestContentFor(spec, importMap, manifestValues) },
    ...blockFiles,
  ];
}

export function modularSpecFilesForYamlIfComplete(specYaml: string | undefined): SynthesizedSpecFile[] | undefined {
  if (!specYaml) {
    return undefined;
  }
  const parsed = load(specYaml);
  if (!isRecord(parsed) || !isCompleteSpecificationShape(parsed) || isRecord(parsed.import)) {
    return undefined;
  }
  return modularSpecFilesFor(parsed);
}

export function specBlockFileNames(files: readonly SynthesizedSpecFile[] | undefined): string[] {
  return (files ?? [])
    .map((file) => file.path)
    .filter((path) => path !== 'specs.yml');
}

function sortedBlockContent(
  block: BlueprintSpecBlock,
  content: Record<string, unknown> | undefined,
): Record<string, unknown> | undefined {
  if (!content || Object.keys(content).length === 0) {
    return undefined;
  }

  const known = new Set(BLOCK_KEY_ORDER[block]);
  const out: Record<string, unknown> = {};
  for (const key of BLOCK_KEY_ORDER[block]) {
    if (Object.prototype.hasOwnProperty.call(content, key)) {
      out[key] = content[key];
    }
  }
  for (const [key, value] of Object.entries(content)) {
    if (!known.has(key)) {
      out[key] = value;
    }
  }
  return out;
}

function manifestValuesFor(spec: Record<string, unknown>): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  if (Object.prototype.hasOwnProperty.call(spec, 'patterns')) {
    out.patterns = spec.patterns;
  }
  return out;
}

function isCompleteSpecificationShape(value: Record<string, unknown>): boolean {
  return isRecord(value.schema)
    && isRecord(value.modes)
    && typeof value.name === 'string'
    && typeof value.initial === 'string'
    && Array.isArray(value.terminal);
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function yamlOptions(): Parameters<typeof dump>[1] {
  return { lineWidth: -1, noRefs: true, sortKeys: false };
}
